(() => {
  const API = 'https://ankhydro-ltd-production.up.railway.app/api';
  const CART_KEY = 'ank_cart';
  let packages = [];
  const loadCart = () => { try { return JSON.parse(localStorage.getItem(CART_KEY)) || { items: [] }; } catch { return { items: [] }; } };
  const saveCart = data => localStorage.setItem(CART_KEY, JSON.stringify(data));
  const esc = v => String(v || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money = n => new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 }).format(Number(n) || 0);
  const selected = () => loadCart().items.filter(i => i.selected !== false);
  const total = () => selected().reduce((sum, i) => sum + i.price * i.quantity, 0);

  function updateCount() { document.getElementById('cartCount').textContent = loadCart().items.reduce((n, i) => n + i.quantity, 0); }
  function addToCart(id) { const pkg = packages.find(p => String(p.id) === String(id)); if (!pkg) return; const data = loadCart(); const item = data.items.find(p => String(p.id) === String(id)); if (item) item.quantity++; else data.items.push({ id: pkg.id, name: pkg.name, price: Number(pkg.price || 0), service: pkg.category || '', quantity: 1, selected: true }); saveCart(data); updateCount(); }
  function renderCart() { const data = loadCart(); const list = document.getElementById('cartItems'); list.innerHTML = data.items.length ? data.items.map(i => `<div class="cart-line"><label><input class="cart-selected" data-id="${i.id}" type="checkbox" ${i.selected !== false ? 'checked' : ''}> ${esc(i.name)}</label><strong>${money(i.price * i.quantity)}</strong><input class="cart-qty" data-id="${i.id}" type="number" min="1" value="${i.quantity}"><button class="cart-remove" data-id="${i.id}" type="button">Remove</button></div>`).join('') : '<p>Your cart is empty.</p>'; document.getElementById('cartTotal').textContent = money(total()); list.querySelectorAll('.cart-selected').forEach(el => el.onchange = () => { const d=loadCart(); d.items.find(i=>String(i.id)===el.dataset.id).selected=el.checked; saveCart(d); renderCart(); }); list.querySelectorAll('.cart-qty').forEach(el => el.onchange = () => { const d=loadCart(); d.items.find(i=>String(i.id)===el.dataset.id).quantity=Math.max(1, Number(el.value)||1); saveCart(d); updateCount(); renderCart(); }); list.querySelectorAll('.cart-remove').forEach(el => el.onclick = () => { const d=loadCart(); d.items=d.items.filter(i=>String(i.id)!==el.dataset.id); saveCart(d); updateCount(); renderCart(); }); }
  function open(id) { document.getElementById(id).classList.add('cart-open'); if(id === 'cartModal') renderCart(); }
  function close(id) { document.getElementById(id).classList.remove('cart-open'); }
  function renderPackages() { const host = document.getElementById('databasePackages'); document.querySelectorAll('.packages-page .package-card').forEach(card => card.closest('section')?.remove()); host.innerHTML = packages.length ? packages.map(p => `<article class="package-card ${p.featured ? 'featured' : ''}"><div class="package-img"><img src="${esc(p.image || 'images/solar-panel-daytime.jpg')}" alt="${esc(p.name)}"></div><h3>${esc(p.name)}</h3><div class="package-price">${Number(p.price)>0 ? money(p.price) : esc(p.priceLabel || 'Call for quote')}</div><ul class="package-specs">${String(p.specs || '').split(',').filter(Boolean).map(s=>`<li>${esc(s.trim())}</li>`).join('')}</ul><div class="card-actions"><a class="btn btn-cyan" href="tel:+254758849293">Call for Quote</a><button class="btn btn-primary add-cart" data-id="${p.id}" type="button">Add to Cart</button></div></article>`).join('') : '<p class="text-center">Coming soon...</p>'; host.querySelectorAll('.add-cart').forEach(btn => btn.onclick = () => addToCart(btn.dataset.id)); }
  async function checkout(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const items = selected(); if (!items.length || total() <= 0) return alert('Select at least one package with a listed price.'); const payload = { customerName: form.get('name'), customerEmail: form.get('email'), phone: form.get('phone'), deliveryAddress: form.get('address'), amount: total(), accountReference: 'ANK-' + Date.now(), transactionDesc: 'ANK Hydro package order', service: items.map(i=>i.service).filter(Boolean).join(', '), packageName: items.map(i=>`${i.name} x ${i.quantity}`).join(', ') }; try { const response = await fetch(API + '/mpesa/pay', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); const d=loadCart(); d.items=d.items.filter(i=>i.selected===false); saveCart(d); updateCount(); close('checkoutModal'); close('cartModal'); alert('STK prompt sent. Confirm payment on your phone.'); } catch (err) { alert(err.message || 'Unable to start payment.'); } }
  function setup() { document.head.insertAdjacentHTML('beforeend', '<style>.cart-trigger{border:0;border-radius:20px;padding:.45rem .75rem;cursor:pointer;font-weight:700}.cart-modal{display:none;position:fixed;inset:0;z-index:3000;background:#0008;align-items:center;justify-content:center;padding:1rem}.cart-modal.cart-open{display:flex}.cart-panel{background:#fff;width:min(620px,100%);max-height:90vh;overflow:auto;border-radius:12px;padding:1.25rem}.cart-line{display:flex;align-items:center;gap:.5rem;justify-content:space-between;padding:.65rem 0;border-bottom:1px solid #ddd}.cart-line label{flex:1}.cart-qty{width:58px}.cart-close{float:right;border:0;background:none;font-size:1.5rem;cursor:pointer}.checkout-form label{display:block;margin:.65rem 0}.checkout-form input,.checkout-form textarea{width:100%;padding:.65rem}.checkout-form textarea{min-height:80px}</style>'); document.querySelector('.nav-wrap').insertAdjacentHTML('beforeend', '<button id="cartButton" type="button" class="cart-trigger">🛒 Cart <span id="cartCount">0</span></button><div id="cartModal" class="cart-modal"><div class="cart-panel"><button class="cart-close" data-close="cartModal">×</button><h2>Your Cart</h2><div id="cartItems"></div><h3>Total: <span id="cartTotal"></span></h3><button id="checkoutButton" class="btn btn-primary" type="button">Checkout</button></div></div><div id="checkoutModal" class="cart-modal"><form id="checkoutForm" class="cart-panel checkout-form"><button class="cart-close" data-close="checkoutModal" type="button">×</button><h2>Confirm M-Pesa order</h2><label>Order total<input id="checkoutTotal" readonly></label><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Delivery address<textarea name="address" required></textarea></label><label>Phone for STK prompt<input name="phone" required placeholder="2547XXXXXXXX"></label><button class="btn btn-primary" type="submit">Send STK prompt</button></form></div>'); document.getElementById('cartButton').onclick=()=>open('cartModal'); document.getElementById('checkoutButton').onclick=()=>{ if(!selected().length||total()<=0) return alert('Select a priced package first.'); document.getElementById('checkoutTotal').value=money(total()); open('checkoutModal'); }; document.querySelectorAll('[data-close]').forEach(btn=>btn.onclick=()=>close(btn.dataset.close)); document.getElementById('checkoutForm').onsubmit=checkout; updateCount(); }
  async function init() { const host = document.getElementById('databasePackages'); if (!host) return; try { const r = await fetch(API + '/site-data?v=' + Date.now()); const data = await r.json(); packages = (data.packages || []).filter(p => p.status === 'active').sort((a,b)=>(a.order||0)-(b.order||0)); } catch { packages = []; } renderPackages(); setup(); }
  document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded', init) : init();
})();
